info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
  dataSource:
    pooled: true
    jmxExport: true
    driverClassName: oracle.jdbc.OracleDriver
    dialect: org.hibernate.dialect.Oracle12cDialect
    username: linksharing
    password: linksharing
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    dbCreate: update
    schema: ORCLPDB1

grails:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "yakash222000@gmail.com"
    password: "ypgt sokp ybcc wlnn"
    props:
      mail.smtp.auth: "true"
      mail.smtp.socketFactory.port: "465"
      mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
      mail.smtp.socketFactory.fallback: "false"

  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html
  controllers:
    defaultScope: singleton
  grails:
    plugin:
      springsecurity:
        userLookup:
          userDomainClassName: com.linksharing.AppUser
          auth:
            loginFormUrl: '/'
            defaultTargetUrl: '/dashboard'
            failureUrl: '/?error=true'
          logout:
            postOnly: false
        securityConfigType: InterceptUrlMap
        interceptUrlMap:
          - pattern: '/'
            access: [ 'permitAll' ]
          - pattern: '/home/**'
            access: [ 'permitAll' ]
          - pattern: '/assets/**'
            access: [ 'permitAll' ]
          - pattern: '/error'
            access: [ 'permitAll' ]
          - pattern: '/**'
            access: [ 'isAuthenticated()' ]

      successHandler:
        defaultTargetUrl: "/dashboard"
      logout:
        afterLogoutUrl: "/"
server:
  address: 0.0.0.0
  PORT: 8080